@_exported import func XCTest.XCTAssertEqual
@_exported import var XCTest.XCT_UI_TESTING_AVAILABLE
@_exported import let XCTest.XCTestErrorDomain
@_exported import struct XCTest.XCTestError
@_exported import class XCTest._XCTestCaseInterruptionException
@_exported import func XCTest._XCTPreformattedFailureHandler
@_exported import func XCTest.XCTAssertThrowsError
@_exported import class XCTest.XCUIElement
@_exported import func XCTest.XCTAssertNil
@_exported import class XCTest.XCTestObserver
@_exported import protocol XCTest.XCTestObservation
@_exported import class XCTest.XCTestObservationCenter
@_exported import class XCTest.XCTIssueReference
@_exported import enum XCTest.XCUIProtectedResource
@_exported import protocol XCTest.XCUIScreenshotProviding
@_exported import func XCTest.XCTAssertNotEqualWithAccuracy
@_exported import class XCTest.XCTExpectedFailure
@_exported import func XCTest.XCTAssertEqualWithAccuracy
@_exported import class XCTest.XCTKVOExpectation
@_exported import func XCTest.XCTAssertTrue
@_exported import class XCTest.XCTMutableIssue
@_exported import class XCTest.XCTDarwinNotificationExpectation
@_exported import class XCTest.XCTestLog
@_exported import protocol XCTest.XCUIElementAttributes
@_exported import class XCTest.XCTSourceCodeSymbolInfo
@_exported import func XCTest.XCTAssertNotIdentical
@_exported import typealias XCTest.XCWaitCompletionHandler
@_exported import let XCTest.XCTestScopeNone
@_exported import let XCTest.XCUIIdentifierCloseWindow
@_exported import struct XCTest.XCUIKeyboardKey
@_exported import class XCTest.XCUIScreenshot
@_exported import let XCTest.XCTestToolKey
@_exported import func XCTest.XCTSkipUnless
@_exported import class XCTest.XCTApplicationLaunchMetric
@_exported import struct XCTest.XCTSkip
@_exported import class XCTest.XCTPerformanceMeasurement
@_exported import let XCTest.XCUIIdentifierZoomWindow
@_exported import class XCTest.XCTNSNotificationExpectation
@_exported import func XCTest.XCTAssertIdentical
@_exported import let XCTest.XCTestScopeAll
@_exported import class XCTest.XCTSourceCodeLocation
@_exported import class XCTest.XCUIElementQuery
@_exported import func XCTest.XCTAssert
@_exported import func XCTest.XCTAssertNoThrow
@_exported import func XCTest.XCTAssertLessThan
@_exported import let XCTest.XCTestObserverClassKey
@_exported import func XCTest._XCTDescriptionForValue
@_exported import func XCTest.XCTAssertNotEqual
@_exported import protocol XCTest.XCUIElementTypeQueryProvider
@_exported import class XCTest.XCTPerformanceMeasurementTimestamp
@_exported import let XCTest.XCTestedUnitPath
@_exported import class XCTest.XCTestSuite
@_exported import func XCTest.XCTAssertNotNil
@_exported import class XCTest.XCUIApplication
@_exported import class XCTest.XCTNSPredicateExpectation
@_exported import class XCTest.XCTAttachment
@_exported import class XCTest.XCUICoordinate
@_exported import class XCTest.XCTOSSignpostMetric
@_exported import enum XCTest.XCUIRemoteButton
@_exported import let XCTest.XCUIIdentifierMinimizeWindow
@_exported import class XCTest.XCTestRun
@_exported import protocol XCTest.XCUIElementSnapshotProviding
@_exported import protocol XCTest.XCUIElementSnapshot
@_exported import func XCTest.XCTFail
@_exported import struct XCTest.XCTPerformanceMetric
@_exported import let XCTest.XCTestScopeKey
@_exported import class XCTest.XCTestProbe
@_exported import func XCTest.XCTAssertGreaterThan
@_exported import class XCTest.XCTestExpectation
@_exported import func XCTest.XCTExpectFailure
@_exported import struct XCTest.XCTIssue
@_exported import enum XCTest._XCTAssertionType
@_exported import func XCTest._XCTFailureFormat
@_exported import func XCTest.XCTAssertFalse
@_exported import func XCTest.XCTAssertGreaterThanOrEqual
@_exported import class XCTest.XCTSourceCodeContext
@_exported import class XCTest.XCTSourceCodeFrame
@_exported import class XCTest.XCTestSuiteRun
@_exported import class XCTest.XCTWaiter
@_exported import func XCTest.XCTSelfTestMain
@_exported import let XCTest.XCUIIdentifierFullScreenWindow
@_exported import protocol XCTest.XCTActivity
@_exported import func XCTest.XCTAssertLessThanOrEqual
@_exported import func XCTest.XCTSkipIf
@_exported import struct XCTest.XCUIGestureVelocity
@_exported import func XCTest.XCTUnwrap
@_exported import protocol XCTest.XCTWaiterDelegate
@_exported import class XCTest._XCTSkipFailureException
@_exported import let XCTest.XCTestScopeSelf
@_exported import class XCTest.XCTContext
@_exported import class XCTest.XCUIScreen
@_exported import class XCTest.XCTestCaseRun
@_exported import func XCTest.XCTAssertEqual

import class XCTest.XCTest

public typealias XCTBeton = XCTest